(END)
    @KBD
    D=M
    @WHITE
    D;JEQ
    @BLACK
    0;JMP
    (WHITE)
        @i
        M=0
        @sum
        M=0
        (LOOP)
            @SCREEN
            D=A
            @i
            D=D+M
            @D
            M=0
            @i
            D=M
            @511
            D=D-A
            @END
            D;JGT
            @i
            M=M+1
            @LOOP
            0;JMP
    (BLACK)
        @i
        M=0
        @sum
        M=0
        (LOOP)
            @SCREEN
            D=A
            @i
            D=D+M
            @D
            M=!0
            @i
            D=M
            @511
            D=D-A
            @END
            D;JGT
            @i
            M=M+1
            @LOOP
            0;JMP